[ado]
address = 'https://ado.glif.link/rpc/v0'

[daemon]
rpc-url = 'https://api.node.glif.io/rpc/v1'

[routes]
agent-deployer = ''
agent-factory = ''
agent-police = ''
cred-parser = ''
ifil = ''
infinity-pool = ''
miner-registry = ''
mock-id-addr-store = ''
pg-donator = ''
pool-registry = ''
prestake = ''
router = ''
system-admin = ''
treasury = ''
vc-issuer-address = ''
wfil = ''
